# Generated by Django 2.1.5 on 2019-01-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazy_light', '0003_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='state',
            new_name='light_on',
        ),
    ]
